version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  celery:
    container_name: celery
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-workers.sh
    volumes:
      - ./data/celery:/data
    depends_on:
      - redis
    links:
      - redis

  flower:
    container_name: flower
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start-flower.sh
    ports:
      - "5555:5555"
    volumes:
      - ./data/celery:/data
    depends_on:
      - redis
    links:
      - redis