version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      DB: "celery"
      DB_USER: "celery"
      DB_PASSWORD: "celery"

  redis:
    container_name: redis
    image: redis:latest
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  celery:
    container_name: celery
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://db:6379/0
    command: ./start-workers.sh
    volumes:
      - ./data/celery:/data
    depends_on:
      - redis
    links:
      - redis

  flower:
    container_name: flower
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://db:6379/0
    command: ./start-flower.sh
    ports:
      - "5555:5555"
    volumes:
      - ./data/celery:/data
    depends_on:
      - redis
    links:
      - redis